name: docsborg
recipe: backdrop
env_file:
  - .env
config:
  php: '7.2'
  webroot: www
  backdrush: 1.x-1.x
  xdebug: true
services:
  database:
    type: mariadb:10.3
    portforward: 3308
  cache:
    type: redis
    persist: true
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/www --uri=https://docsborg.lndo.site
  redis-cli:
    service: cache
  pull-db:
    service: appserver
    description: 'Get the latest DB from docs.backdropcms.org'
    cmd:
      - appserver: php /app/scripts/pull-db-files.php --database
      - database: /helpers/sql-import.sh docs-latest-sanitized.sql.gz
      - appserver: rm -f docs-latest-sanitized.sql.gz
  pull-files:
    service: appserver
    description: 'Get the latest files from docs.backdropcms.org'
    cmd:
      - php /app/scripts/pull-db-files.php --files
      - tar -xzf docs-files-latest.tar.gz
      - rm -r www/files/ || true
      - mv files/ www/
      - rm -f docs-files-latest.tar.gz
