# Backdrop recipe
name: apiborg
recipe: backdrop
env_file:
  - .env
config:
  php: '7.2'
  webroot: www
  backdrush: 1.x-1.x
  xdebug: true
services:
  database:
    type: mariadb:10.3
    portforward: 3308
  cache:
    type: redis
    persist: true
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/www --uri=https://apiborg.lndo.site
  redis-cli:
    service: cache
  pull-db:
    service: appserver
    description: 'Pull the latest DB from api.backdropcms.org'
    cmd:
      - appserver: php /app/scripts/pull-db-files.php --database
      - database: /helpers/sql-import.sh api_backdrop-latest-sanitized.sql.gz
      - appserver: rm -f api_backdrop-latest-sanitized.sql.gz
  pull-files:
    service: appserver
    description: 'Pull the latest files from api.backdropcms.org'
    cmd:
      - php /app/scripts/pull-db-files.php --files
      - tar -xzf api_backdrop-files-latest.tar.gz
      - mv files/ www/
      - rm -f api_backdrop-files-latest.tar.gz

