<?php
/**
 * @file
 * Custom module for the Backdrop API site.
 */

/**
 * Implements hook_block_info().
 */
function backdropapi_block_info() {
  $blocks['form_api_table'] = array(
    'info' => t('Form API table'),
    'description' => t('Displays all Form API elements and properties together in a table.'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function backdropapi_block_view($delta = '', $settings = array(), $contexts = array()) {
  $block = array();

  if ($delta == 'form_api_table') {
    $block['subject'] = '';
    $block['content'] = backdropapi_form_api_table();
  }

  return $block;
}

/**
 * Returns a table of Form API elements and properties.
 */
function backdropapi_form_api_table() {
  // Get lists of Form API elements & properties.
  $elements = views_get_view_result('form_api', 'attachment_1');
  $properties = views_get_view_result('form_api', 'attachment_2');

  // Setup the table headers.
  $header_elements = array('');
  $header_special = $header_elements;
  foreach ($elements as $element) {
    $value = '<a href="#' . $element->node_title . '">' . $element->node_title . '</a>';

    if (!empty($element->field_field_special) && $element->field_field_special[0]['raw']['value']) {
      $header_special[] = $value;
    }
    else {
      $header_elements[] = $value;
    }
  }

  // Setup the table rows.
  $mark = '&#10003;'; // checkmark
  foreach ($properties as $property) {
    $id_suffix = in_array($property->node_title, backdropapi_form_api_elements()) ? '_property' : '';
    $row_element = array('<a href="#' . $property->node_title . $id_suffix . '">#' . $property->node_title . '</a>');
    $row_special = $row_element;

    foreach ($elements as $element) {
      // Get all properties for this element.
      $element_properties = array();
      foreach ($element->field_field_fapi_properties as $element_property) {
        $element_properties[] = $element_property['rendered']['entity']['paragraphs_item'][$element_property['raw']['value']]['field_fapi_property'][0]['#markup'];
      }

      // Set the value of the cell.
      $value = '';
      if (in_array($property->node_title, $element_properties)) {
        $value = $mark;
      }

      if (!empty($element->field_field_special) && $element->field_field_special[0]['raw']['value']) {
        $row_special[] = $value;
      }
      else {
        $row_element[] = $value;
      }
    }

    // Only display non-empty rows in each table.
    if (in_array($mark, $row_element)) {
      $rows_elements[] = $row_element;
    }
    if (in_array($mark, $row_special)) {
      $rows_special[] = $row_special;
    }
  }

  // Theme the tables.
  $heading_elements = '<h3 id="input-elements">' . t('Input elements') . '</h3>';
  $table_elements = theme('table', array(
    'header' => $header_elements,
    'rows' => $rows_elements,
    'attributes' => array('class' => array('form-api')),
  ));
  $heading_special = '<h3 id="special-elements">' . t('Structure elements') . '</h3>';
  $table_special = theme('table', array(
    'header' => $header_special,
    'rows' => $rows_special,
    'attributes' => array('class' => array('form-api')),
  ));

  return $heading_elements . $table_elements . $heading_special . $table_special;
}

/**
 * Get a list of all Form API elements.
 */
function backdropapi_form_api_elements() {
  $elements = &backdrop_static(__FUNCTION__);

  if (!isset($elements)) {
    $results = views_get_view_result('form_api', 'attachment_5');

    foreach ($results as $result) {
      $elements[] = $result->node_title;
    }
  }

  return $elements;
}
