<?php

/**
 * Implements hook_menu().
 */
function unfeaturize_menu() {
  $items['admin/config/development/unfeaturize'] = array(
    'title' => 'Unfeaturize content types',
    'description' => 'Take your content types away from features and put them back in the database where they belong.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('unfeaturize_admin_form'),
    'access arguments' => array('administer content types'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function unfeaturize_admin_form() {
  $types = node_type_get_types();
  $options = array();
  foreach ($types as $key => $type) {
    $options[$key] = $type->name;
  }

  $form = array();

  $form['message'] = array(
    '#markup' => '<p>' . t('First disable any modules providing the content type you would like to put back in the database.') . '</p>',
  );

  $form['types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Which types would you like to unfeaturize?'),
    '#options' => $options,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Unfeaturize'),
  );

  return $form;
}


function unfeaturize_admin_form_submit(&$form, &$form_state) {
  // Loop through each and unlock the content type.
  foreach ($form_state['values']['types'] as $ctype) {
    if ($ctype) {
      db_query("UPDATE {node_type} SET `custom` = 1, `locked` = 0, `module` = 'node', `orig_type` = :type 
        WHERE `type` = :type", array(':type' => $ctype));

      drupal_set_message(t('The content type <em>!type</em> has been restored in the database.', array('!type' => $ctype)));
    }
  }

  // Clean Drupal cache; this is necessary for the "Delete" link to appear
  // next to the content type created by the feature.
  drupal_flush_all_caches();
}
