<?php
/**
 * @file
 * Install, update, and uninstall functions for the Feeds JSONPath Parser
 * module.
 */

/**
 * Implements hook_enable().
 */
function feeds_jsonpath_parser_enable() {
  // Clear Feeds' plugin cache so that this plugin shows up.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}

/**
 * Delete JSONPath Parser variables.
 */
function feeds_jsonpath_parser_update_1000() {
  // Delete variables.
  update_variable_del('feeds_jsonpath_library_dir');
}

