<?php
/**
 * @file
 * Parse a JSON document using JSONPath.
 */

/**
 * Implements hook_autoload_info().
 */
function feeds_jsonpath_parser_autoload_info() {
  return array(
    'Flow\JSONPath\JSONPath' => 'libraries/JSONPath/src/Flow/JSONPath/JSONPath.php',
    'Flow\JSONPath\JSONPathException' => 'libraries/JSONPath/src/Flow/JSONPath/JSONPathException.php',
    'Flow\JSONPath\JSONPathLexer' => 'libraries/JSONPath/src/Flow/JSONPath/JSONPathLexer.php',
    'Flow\JSONPath\JSONPathToken' => 'libraries/JSONPath/src/Flow/JSONPath/JSONPathToken.php',
    'Flow\JSONPath\AccessHelper' => 'libraries/JSONPath/src/Flow/JSONPath/AccessHelper.php',

    'Flow\JSONPath\Filters\AbstractFilter' => 'libraries/JSONPath/src/Flow/JSONPath/Filters/AbstractFilter.php',
    'Flow\JSONPath\Filters\IndexesFilter' => 'libraries/JSONPath/src/Flow/JSONPath/Filters/IndexesFilter.php',
    'Flow\JSONPath\Filters\IndexFilter' => 'libraries/JSONPath/src/Flow/JSONPath/Filters/IndexFilter.php',
    'Flow\JSONPath\Filters\QueryMatchFilter' => 'libraries/JSONPath/src/Flow/JSONPath/Filters/QueryMatchFilter.php',
    'Flow\JSONPath\Filters\QueryResultFilter' => 'libraries/JSONPath/src/Flow/JSONPath/Filters/QueryResultFilter.php',
    'Flow\JSONPath\Filters\RecursiveFilter' => 'libraries/JSONPath/src/Flow/JSONPath/Filters/RecursiveFilter.php',
    'Flow\JSONPath\Filters\SliceFilter' => 'libraries/JSONPath/src/Flow/JSONPath/Filters/SliceFilter.php',

    'FeedsJSONPathParser' => 'FeedsJSONPathParser.inc',
  );
}

/**
 * Implements hook_feeds_plugins().
 */
function feeds_jsonpath_parser_feeds_plugins() {
  return array(
    'FeedsJSONPathParser' => array(
      'module' => 'feeds_jsonpath_parser',
      'name' => t('JSONPath parser'),
      'description' => t('Parse JSON files using JSONPath.'),
      'handler' => array(
        'parent' => 'FeedsParser',
        'class' => 'FeedsJSONPathParser',
        'file' => 'FeedsJSONPathParser.inc',
        'path' => backdrop_get_path('module', 'feeds_jsonpath_parser'),
      ),
    ),
  );
}

